main:
  - name: Home
    url: /
    weight: 10
  - name: Books
    url: #publications
    weight: 20
  - name: Events
    url: #events
    weight: 30
  - name: "About"
    url: "#about"
    weight: 40
  - name: Book me
    url: #about
    weight: 40
  - name = "Contact"
    url = "#contact"
    weight = 60